cart/urls.py
#!/usr/bin/python3
"""here is the urls, the routing of cart application"""
from django.urls import path

from cart.views import (cart_add, cart_remove, cart_detail,)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove,
         name='cart_remove'),

]

chapchap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('cart/', include('cart.urls')),
    path('myaccount/', include('myaccount.urls')),
    path('orders/', include('orders.urls')),
    path('store/', include('store.urls')),
    path('summernote/', include('django_summernote.urls')), # for summernote
]
if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.page_not_found_view'

myaccount/urls.py
"""routes of myaccount application"""
from django.contrib.auth.views import LogoutView
from django.urls import path

import myaccount
from myaccount.views import dashboard
app_name = 'myaccount'

urlpatterns = [
    path('dashboard/',dashboard, name='dashboard'),
    path('logout/', LogoutView.as_view(), name='logout'),  # extending  Django built in logout
]

store/urls.py
#!/usr/bin/python3
"""here is the urls, the routing of store application"""
from django.urls import path

from store.views import (StoreListView, StoreCreateView, StoreUpdateView,
                         ProductListView, ProductCreateView,
                         ProductUpdateView, StoreDeleteView,
                         ProductDeleteView, StoreListQrcodeView, MyView,
                         MyViewPdf, QRcodeView)

app_name = 'store'

urlpatterns = [
    path('list-store/', StoreListView.as_view(), name='list-store'),
    path('list-store-qrcode/', StoreListQrcodeView.as_view(), name='list-store-qrcode'),
    path('generate-qrstore/', MyView.as_view(), name='generate-qrstore'),
    path('generate-pdf/<uuid:code>', MyViewPdf.as_view(), name='generate-pdf'),
    # path('generate-pdf/', MyViewPdf.as_view(), name='generate-pdf'),
    path('generate-qrstore-pdf/', QRcodeView.as_view(), name='generate-qrstore-pdf'),
    path('add-store/', StoreCreateView.as_view(), name='add-store'),
    path('edit-store/<int:pk>', StoreUpdateView.as_view(), name='edit-store'),
    path('delete-store/<int:pk>', StoreDeleteView.as_view(), name='del-store'),
    path('list-product/', ProductListView.as_view(), name='list-product'),
    path('add-product/', ProductCreateView.as_view(), name='add-product'),
    path('edit-product/<int:pk>', ProductUpdateView.as_view(),
         name='edit-product'),
    path('delete-product/<int:pk>', ProductDeleteView.as_view(),
         name='del-product'),

]

store/forms.py
#!/usr/bin/env python

""" Store creation Form"""
from django.utils.safestring import mark_safe
from django import forms
from django.forms import ModelForm
from django_summernote.widgets import SummernoteWidget

from store.models import Store, Product, Category


class ProductForm(ModelForm):

    class Meta:
        model = Product

        fields = ('name', 'description',  'category', 'store', 'price', 'productimage')

        labels = {
            "name": mark_safe('Name<span class="text-danger">*</span>'),
            "description": mark_safe('Description<span class="text-danger">*</span>'),
            "category": mark_safe('Category<span class="text-danger">*</span>'),
            "store": mark_safe('Store<span class="text-danger">*</span>'),
            "price": mark_safe('Price<span class="text-danger">*</span>'),
            "photo": mark_safe('Photo<span class="text-danger">*</span>'),
        }

        widgets = {
            "name": forms.TextInput(attrs={'class': 'form-control'}),
            "description": SummernoteWidget(attrs={'class': 'form-control'}),
            "category": forms.Select(attrs={'class': 'form-control'}),
            "store": forms.Select(attrs={'class': 'form-control'}),
            "price": forms.TextInput(attrs={'class': 'form-control'}),
            "photo": forms.FileInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, user, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.request = kwargs.pop('request', None)
        self.user = user
        print("Proprio", user)

        self.fields['store'].queryset = Store.objects.filter(proprietary=self.user)
        self.fields['category'].queryset = Category.objects.all()

        print("store", self.fields['store'].queryset)




class StoreForm(ModelForm):
    class Meta:
        model = Store

        fields = ("name", "phone", "description", "photo")

        labels = {
            "name": mark_safe('Name<span class="text-danger">*</span>'),
            "phone": mark_safe('Phone<span class="text-danger">*</span>'),
            "description": mark_safe('Description<span class="text-danger">*</span>'),
            "photo": mark_safe('Photo<span class="text-danger">*</span>'),
        }

        widgets = {
            "name": forms.TextInput(attrs={'class': 'form-control'}),
            "phone": forms.TextInput(attrs={'class': 'form-control'}),
            "description": SummernoteWidget(attrs={'class': 'form-control'}),
            "photo": forms.FileInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, user, *args, **kwargs):
        super(StoreForm, self).__init__(*args, **kwargs)
        self.request = kwargs.pop('request', None)
        self.user = user

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if not phone:
            raise forms.ValidationError('Ce champ est requis')
        else:
            if not phone.isdigit():
                raise forms.ValidationError('Phone must be digits')

        return phone

    def clean_name(self):
        name = self.cleaned_data['name']
        if not name:
            raise forms.ValidationError('Ce champ est requis')
        return name

    def clean_photo(self):
        photo = self.cleaned_data['photo']
        if not photo:
            raise forms.ValidationError('Ce champ est requis')
        return photo

store/views.py
#!/usr/bin/env python
"""views function and class to manage store and is contents(products)
"""
import base64
import io
from io import BytesIO

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, get_object_or_404
from django.template.loader import get_template

from django.urls import reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from chapchap import settings
from frontend.models import Utilisateur
from store.forms import StoreForm, ProductForm
from store.models import Store, Product
from django.views.generic import View
from django.http import HttpResponse
from xhtml2pdf import pisa
import qrcode


class StoreListView(LoginRequiredMixin, ListView):
    template_name = 'store/list-store.html'
    # queryset = Store.objects.all()
    model = Store

    # context_object_name = 'stores'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        utilisateur = Utilisateur.objects.get(email=self.request.user.email)

        if (self.request.user.is_authenticated and utilisateur.is_admin):
            stores = Store.objects.all()

        else:
            stores = Store.objects.filter(proprietary=utilisateur)
            # stores = Store.objects.all()

        print('utilisateur', utilisateur.id)
        print('store', stores)
        context['stores'] = stores
        return context


from django.views.generic import View
from django.shortcuts import render
import qrcode


class QRcodeView(View):
    def get(self, request, *args, **kwargs):
        # Generate the QR code
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data('This is the data for the QR code')
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")

        # Create an in-memory buffer containing the image data
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        buffer.seek(0)

        base64_image = base64.b64encode(buffer.read()).decode('utf-8')

        print(base64_image)

        # Render the template and pass the image data to the template
        return render(request, 'store/mytemplateqrcode.html', {'base64_image': base64_image})


class MyView(View):
    def get(self, request, *args, **kwargs):
        # Generate the QR code
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data('This is the data for the QR code')
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")

        # Create an HttpResponse and set the appropriate headers
        response = HttpResponse(content_type='image/png')
        response['Content-Disposition'] = 'inline; filename=qrcode.png'

        # Write the QR code image to the response
        img.save(response, 'PNG')
        return response


class MyViewPdf(View):
    def get(self, request, *args, **kwargs):
        """Render qrcode"""
        template = get_template('store/mytemplate.html')
        code = kwargs.get('code')
        print('kwargs', str(code))
        store = None
        if str(code):
            store = get_object_or_404(Store, code=code)
        else:
            return HttpResponse('Error generating PDF, no valid store code', status=400)
        # from settings.py, BASE_URL is configured
        BASE_URL = settings.BASE_URL

        store_relative_url = store.get_absolute_url()
        store_absolute_url = BASE_URL + reverse('frontend:detail-store', args=[code])


        # print(store_relative_url, store_absolute_url)

        # Generate the QR code
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=20,
            border=4,
        )
        qr.add_data(store_absolute_url)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")

        # Create an in-memory buffer containing the image data
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        buffer.seek(0)

        base64_image = base64.b64encode(buffer.read()).decode('utf-8')

        context = {
            'data': store_absolute_url,
            'base64_image': base64_image
        }
        html = template.render(context)

        # Create a PDF from the HTML
        result = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html.encode('UTF-8')), result)
        if not pdf.err:
            response = HttpResponse(result.getvalue(), content_type='application/pdf')
            # response['Content-Disposition'] = 'attachment; filename=mypdf.pdf' # is download
            response['Content-Disposition'] = 'inline; filename=qrcode.pdf'
            return response
        return HttpResponse('Error generating PDF', status=400)


class StoreListQrcodeView(LoginRequiredMixin, ListView):
    template_name = 'store/list-store-qrcode.html'
    # queryset = Store.objects.all()
    model = Store

    # context_object_name = 'stores'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        utilisateur = Utilisateur.objects.get(email=self.request.user.email)

        if (self.request.user.is_authenticated and utilisateur.is_admin):
            stores = Store.objects.all()

        else:
            stores = Store.objects.filter(proprietary=utilisateur)
            # stores = Store.objects.all()

        print('utilisateur', utilisateur.id)
        print('store', stores)
        context['stores'] = stores
        return context


class StoreCreateView(LoginRequiredMixin, CreateView, SuccessMessageMixin):
    """Class based view to create a store"""
    template_name = 'store/add-store.html'
    model = Store
    form_class = StoreForm
    context_object_name = 'store'

    success_message = 'Store created successfully'

    def get_success_url(self):
        return reverse('store:list-store')

    def get_form_kwargs(self):
        kwargs = super(StoreCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        objStore = form.save(commit=False)
        objStore.proprietary = Utilisateur.objects.get(email=self.request.user.email)
        objStore.save()
        return super(StoreCreateView, self).form_valid(form)


class StoreUpdateView(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
    """Class based view to update a store"""
    template_name = 'store/edit-store.html'
    model = Store
    form_class = StoreForm
    context_object_name = 'store'

    success_message = 'Store edited successfully'

    def get_success_url(self):
        return reverse('store:list-store')

    def get_object(self, queryset=None):
        """ Hook to ensure object. """
        obj = super(StoreUpdateView, self).get_object()
        return obj

    def get_form_kwargs(self):
        kwargs = super(StoreUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        objStore = form.save(commit=False)
        # objStore.proprietary = Utilisateur.objects.get(email=self.request.user.email)
        objStore.save()

        return super(StoreUpdateView, self).form_valid(form)


class StoreDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    """Class based view to delete a store"""
    model = Store
    template_name = "store/delete-store.html"
    context_object_name = "store"

    success_message = "Store deleted successfully."

    def get_success_url(self):
        return reverse("store:list-store")


class StoreDetailsView(LoginRequiredMixin, DetailView):
    template_name = 'store/detail-store.html'
    model = Store
    context_object_name = 'store'


class ProductListView(LoginRequiredMixin, ListView):
    template_name = 'product/list-product.html'
    # queryset = Store.objects.all()
    model = Product

    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = None

        utilisateur = Utilisateur.objects.get(email=self.request.user.email)

        thestores = Store.objects.filter(proprietary=utilisateur)
        nbre = len(thestores)

        context['has_stores'] = True if nbre > 0 else False

        if (self.request.user.is_authenticated and utilisateur.is_admin):
            products = Product.objects.all()

        else:

            products = Product.objects.select_related('store__proprietary').filter(store__proprietary_id=utilisateur.id)

        context['products'] = products
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    template_name = 'product/add-product.html'
    # queryset = Store.objects.all()
    model = Product
    form_class = ProductForm

    context_object_name = 'product'

    def get_success_url(self):
        return reverse('store:list-product')

    """def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        proprietary = Utilisateur.objects.get(telephone=self.request.user.telephone)

        store = Store.objects.filter(proprietary= proprietary)
        print(type(store))

        context['store'] = store[1]

        return context

        print('proprietary', proprietary)"""

    def get_form_kwargs(self):
        kwargs = super(ProductCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user

        return kwargs


class ProductUpdateView(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
    template_name = 'product/edit-product.html'
    model = Product
    form_class = ProductForm

store/templates/store/list-storesve.html
{% extends 'base.html'%}
{% load static%}
{% block title %}CHAPCHAP|| My stores  {% endblock %}

{% block css %}
{# add some css link here#}
    <!-- CSS
    ============================================ -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/flaticon/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick-theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/sal.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/chapchap.css' %}">
{% endblock %}


{% block content %}

{% include 'myaccount/myheader.html' %}


    <main class="main-wrapper">
        <!-- Start Breadcrumb Area  -->
        <div class="axil-breadcrumb-area">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-8">
                        <div class="inner">
                            <ul class="axil-breadcrumb">
                                <li class="axil-breadcrumb-item"><a href="{% url 'myaccount:dashboard' %}">Home</a></li>
                                <li class="separator"></li>
                                <li class="axil-breadcrumb-item active" aria-current="page">My Stores</li>
                            </ul>
                            <h1 class="title">Explore All Stores <a class="axil-btn btn-outline" href="{% url 'store:add-store' %}"><i class="fas fa-shopping-bag"></i> add a store</a></h1>

                        </div>
                    </div>
                    <div class="col-lg-6 col-md-4">
                        <div class="inner">
                            <div class="bradcrumb-thumb">
                                <img src="{% static 'assets/images/product/product-45.png' %}" alt="Image">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Breadcrumb Area  -->
        <!-- Start Shop Area  -->
        <div class="axil-shop-area axil-section-gap bg-color-white">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="axil-shop-top d-none">
                            <div class="row ">
                                <div class="col-lg-9">
                                    <div class="category-select">

                                        <!-- Start Single Select  -->
                                        <select class="single-select">
                                            <option>Categories</option>
                                            <option>Fashion</option>
                                            <option>Electronics</option>
                                            <option>Furniture</option>
                                            <option>Beauty</option>
                                        </select>
                                        <!-- End Single Select  -->

                                        <!-- Start Single Select  -->
                                        <select class="single-select">
                                            <option>Color</option>
                                            <option>Red</option>
                                            <option>Blue</option>
                                            <option>Green</option>
                                            <option>Pink</option>
                                        </select>
                                        <!-- End Single Select  -->

                                        <!-- Start Single Select  -->
                                        <select class="single-select">
                                            <option>Price Range</option>
                                            <option>0 - 100</option>
                                            <option>100 - 500</option>
                                            <option>500 - 1000</option>
                                            <option>1000 - 1500</option>
                                        </select>
                                        <!-- End Single Select  -->

                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="category-select mt_md--10 mt_sm--10 justify-content-lg-end">
                                        <!-- Start Single Select  -->
                                        <select class="single-select">
                                            <option>Sort by Latest</option>
                                            <option>Sort by Name</option>
                                            <option>Sort by Price</option>
                                            <option>Sort by Viewed</option>
                                        </select>
                                        <!-- End Single Select  -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row--15">
                    {% for store in stores %}
                    <div class="col-xl-3 col-lg-4 col-sm-6">
                        <div class="axil-product product-style-one has-color-pick mt--40">
                            <div class="thumbnail">
                                <a href="{% url 'store:edit-store' store.id %}">
                                    <img src="{{ store.photo.url }}" alt="{{ store.name }}">

                                </a>
                                <div class="label-block label-right d-none">
                                    <div class="product-badget d-none">20% OFF</div>
                                </div>
                                <div class="product-hover-action">
                                    <ul class="cart-action">
                                        <li class="wishlist d-none"><a href="wishlist.html"><i class="far fa-heart"></i></a></li>
                                        <li class="select-option d-none"><a href="cart.html">Add to Cart</a></li>
                                        <li class="quickview d-none"><a href="#" data-bs-toggle="modal" data-bs-target="#quick-view-modal"><i class="far fa-eye"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="product-content">
                                <div class="inner">
                                    <h5 class="title">{{ store.name }}  <a class="edit" href="{% url 'store:edit-store' store.id %}"><i class="far fa-edit"></i>edit</a> <a class="delete" href="{% url 'store:del-store' store.id %}"><i class="fas fa-trash"></i>del.</a></h5>
                                    <div class="product-price-variant d-none">
                                        <span class="price current-price">$30</span>
                                        <span class="price old-price">$30</span>
                                    </div>
                                    <div class="color-variant-wrapper d-none">
                                        <ul class="color-variant">
                                            <li class="color-extra-01 active"><span><span class="color"></span></span>
                                            </li>
                                            <li class="color-extra-02"><span><span class="color"></span></span>
                                            </li>
                                            <li class="color-extra-03"><span><span class="color"></span></span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <!-- End Single Product  -->
                </div>
                <div class="text-center pt--30 d-none">
                    <a href="#" class="axil-btn btn-bg-lighter btn-load-more">Load more</a>
                </div>
            </div>
            <!-- End .container -->
        </div>
        <!-- End Shop Area  -->
        <!-- Start Axil Newsletter Area  -->
        <div class="axil-newsletter-area axil-section-gap pt--0">
            <div class="container">
                <div class="etrade-newsletter-wrapper bg_image bg_image--5">
                    <div class="newsletter-content">
                        <span class="title-highlighter highlighter-primary2"><i class="fas fa-envelope-open"></i>Newsletter</span>
                        <h2 class="title mb--40 mb_sm--30">Get weekly update</h2>
                        <div class="input-group newsletter-form">
                            <div class="position-relative newsletter-inner mb--15">
                                <input placeholder="example@gmail.com" type="text">
                            </div>
                            <button type="submit" class="axil-btn mb--15">Subscribe</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End .container -->
        </div>
        <!-- End Axil Newsletter Area  -->
    </main>


{% include 'myaccount/footer.html' %}




{% include 'myaccount/cart-dropdown.html' %}

    <!-- JS
============================================ -->
    <!-- Modernizer JS -->
    <script src="{% static 'assets/js/vendor/modernizr.min.js' %}"></script>
    <!-- jQuery JS -->
    <script src="{% static 'assets/js/vendor/jquery.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/js.cookie.js' %}"></script>
    <!-- <script {% static 'src="assets/js/vendor/jquery.style.switcher.js' %}"></script> -->
    <script src="{% static 'assets/js/vendor/jquery-ui.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/sal.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/counterup.js' %}"></script>
    <script src="{% static 'assets/js/vendor/waypoints.min.js' %}"></script>

    <!-- Main JS -->
    <script src="{% static 'assets/js/main.js' %}"></script>


{% endblock %}

store/templates/store/mytemplate.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CHAPCHAP|| Store QRcode {% endblock %}

{% block css %}
    {# add some css link here#}
    <!-- CSS
    ============================================ -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/flaticon/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick-theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/sal.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/base.css' %}">
    <link href="{% static 'assets/vendor/datatables/datatables.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/chapchap.css' %}">
    <style>
    .red {
        color: red;
        text-align: center;
    }
    .qrcode {

        text-align: center;
        margin-top: 200px;
    }
    </style>
{% endblock %}
{% block content %}

<h1 class="red text-center">Please scan this code to visit my store.</h1>
    <br>
    <br>
<img class="qrcode ml-5 mt-5" src="data:image/png;base64,{{ base64_image }}" alt="QR code">

    </div>
{% endblock %}

store/templates/store/mytemplateqrcode.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CHAPCHAP|| Add Store  {% endblock %}

{% block css %}
    {# add some css link here#}
    <!-- CSS
    ============================================ -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/flaticon/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/slick-theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/sal.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/vendor/base.css' %}">
    <link href="{% static 'assets/vendor/datatables/datatables.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/chapchap.css' %}">
    <style>
    .red {
        color: red;
        text-align: center;
    }
    </style>
{% endblock %}
{% block content %}
        <div class="axil-dashboard-area axil-section-gap">
            <div class="container">

<h1 class="red text-center">Salam</h1>
<img class="w-50 text-center" src="data:image/png;base64,{{ base64_image }}" alt="QR code">
            </div>
            </div>
{% endblock %}