cart/urls.py
#!/usr/bin/python3
"""here is the urls, the routing of cart application"""
from django.urls import path

from cart.views import (cart_add, cart_remove, cart_detail,)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove,
         name='cart_remove'),

]

chapchap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('cart/', include('cart.urls')),
    path('myaccount/', include('myaccount.urls')),
    path('orders/', include('orders.urls')),
    path('store/', include('store.urls')),
    path('summernote/', include('django_summernote.urls')), # for summernote
]
if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.page_not_found_view'

frontend/urls.py
#!/usr/bin/env python3
"""This module is about urls of frontend app
"""
from django.urls import path

from frontend.controller.LoginPage import LoginPageView
from frontend.controller.SignupPage import SignUpView
from frontend.views import accueil, resetpassword, listofstore,\
                        storedetails, productdetails, StoreListView, ShopListView

app_name = 'frontend'
urlpatterns = [
    path('', accueil, name='index'),
    path('login/', LoginPageView.as_view(), name='login'),
    path('reset-password/', resetpassword, name='reset-password'),
    # path('stores/', listofstore, name='stores'),
    path('stores/', StoreListView.as_view(), name='stores'),
    path('shop/', ShopListView.as_view(), name='shop'),
    #path('detail-store/<int:pk>',storedetails, name='detail-store'),
    path('detail-store/<uuid:pk>', storedetails, name='detail-store'),
    path('detail-product/<int:pk>', productdetails, name='detail-product'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

store/urls.py
#!/usr/bin/python3
"""here is the urls, the routing of store application"""
from django.urls import path

from store.views import (StoreListView, StoreCreateView, StoreUpdateView,
                         ProductListView, ProductCreateView,
                         ProductUpdateView, StoreDeleteView,
                         ProductDeleteView, StoreListQrcodeView, MyView,
                         MyViewPdf, QRcodeView)

app_name = 'store'

urlpatterns = [
    path('list-store/', StoreListView.as_view(), name='list-store'),
    path('list-store-qrcode/', StoreListQrcodeView.as_view(), name='list-store-qrcode'),
    path('generate-qrstore/', MyView.as_view(), name='generate-qrstore'),
    path('generate-pdf/<uuid:code>', MyViewPdf.as_view(), name='generate-pdf'),
    # path('generate-pdf/', MyViewPdf.as_view(), name='generate-pdf'),
    path('generate-qrstore-pdf/', QRcodeView.as_view(), name='generate-qrstore-pdf'),
    path('add-store/', StoreCreateView.as_view(), name='add-store'),
    path('edit-store/<int:pk>', StoreUpdateView.as_view(), name='edit-store'),
    path('delete-store/<int:pk>', StoreDeleteView.as_view(), name='del-store'),
    path('list-product/', ProductListView.as_view(), name='list-product'),
    path('add-product/', ProductCreateView.as_view(), name='add-product'),
    path('edit-product/<int:pk>', ProductUpdateView.as_view(),
         name='edit-product'),
    path('delete-product/<int:pk>', ProductDeleteView.as_view(),
         name='del-product'),

]

frontend/views.py
#!/usr/bin/env python3
"""This module is about : views.py
"""
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from el_pagination.views import AjaxListView
from store.models import Category, Store, Product
from cart.forms import CartAddProductForm


def page_not_found_view(request, exception):
    """page not found function
    """
    context = {}
    return render(request, 'frontend/404.html', context)


def accueil(request):
    """Home page function"""
    categories = Category.objects.all()
    stores = Store.objects.all()
    print('categories', categories)

    context = {
        'categories': categories,
        'stores': stores,
    }
    return render(request, 'frontend/home.html', context)


def listofstore(request):
    stores = Store.objects.all()
    print("stores", stores)
    context = {
        'stores': stores,
    }
    return render(request, 'frontend/store.html', context)


def productdetails(request, pk):
    otherproducts = None
    product = get_object_or_404(Product, pk=pk)
    if product is not None:
        otherproducts = Product.objects.filter(Q(store_id=product.store.id) & ~Q(id__in=[product.pk,]))
        print('otherproducts', otherproducts)

    cart_form = CartAddProductForm()

    context = {
        'product': product,
        'otherproducts': otherproducts,
        'cart_form': cart_form,

    }
    return render(request, 'frontend/detail-product.html', context)


def storedetails(request, pk):
    products = None
    store = get_object_or_404(Store, code=pk)
    if store is not None:
        products = Product.objects.filter(store=store)
        print('products', products)

    context = {
        'products': products,
        'store': store,
    }
    return render(request, 'frontend/detail-store.html', context)


def resetpassword(request):
    return render(request, 'frontend/forgot-password.html')


class StoreListView(AjaxListView):
    """Class for pagination of store list"""
    context_object_name = 'stores'
    template_name = 'frontend/store.html'
    page_template = 'frontend/store-list-ajax.html'

    def get_queryset(self):
        return Store.objects.all()

class ShopListView(AjaxListView):
    """Class for pagination of product list"""
    context_object_name = 'products'
    template_name = 'frontend/shop.html'
    page_template = 'frontend/shop-list-ajax.html'

    def get_queryset(self):
        return Product.objects.all()

store/views.py
#!/usr/bin/env python
"""views function and class to manage store and is contents(products)
"""
import base64
import io
from io import BytesIO

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, get_object_or_404
from django.template.loader import get_template

from django.urls import reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from chapchap import settings
from frontend.models import Utilisateur
from store.forms import StoreForm, ProductForm
from store.models import Store, Product
from django.views.generic import View
from django.http import HttpResponse
from xhtml2pdf import pisa
import qrcode


class StoreListView(LoginRequiredMixin, ListView):
    template_name = 'store/list-store.html'
    # queryset = Store.objects.all()
    model = Store

    # context_object_name = 'stores'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        utilisateur = Utilisateur.objects.get(email=self.request.user.email)

        if (self.request.user.is_authenticated and utilisateur.is_admin):
            stores = Store.objects.all()

        else:
            stores = Store.objects.filter(proprietary=utilisateur)
            # stores = Store.objects.all()

        print('utilisateur', utilisateur.id)
        print('store', stores)
        context['stores'] = stores
        return context


from django.views.generic import View
from django.shortcuts import render
import qrcode


class QRcodeView(View):
    def get(self, request, *args, **kwargs):
        # Generate the QR code
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data('This is the data for the QR code')
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")

        # Create an in-memory buffer containing the image data
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        buffer.seek(0)

        base64_image = base64.b64encode(buffer.read()).decode('utf-8')

        print(base64_image)

        # Render the template and pass the image data to the template
        return render(request, 'store/mytemplateqrcode.html', {'base64_image': base64_image})


class MyView(View):
    def get(self, request, *args, **kwargs):
        # Generate the QR code
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data('This is the data for the QR code')
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")

        # Create an HttpResponse and set the appropriate headers
        response = HttpResponse(content_type='image/png')
        response['Content-Disposition'] = 'inline; filename=qrcode.png'

        # Write the QR code image to the response
        img.save(response, 'PNG')
        return response


class MyViewPdf(View):
    def get(self, request, *args, **kwargs):
        """Render qrcode"""
        template = get_template('store/mytemplate.html')
        code = kwargs.get('code')
        print('kwargs', str(code))
        store = None
        if str(code):
            store = get_object_or_404(Store, code=code)
        else:
            return HttpResponse('Error generating PDF, no valid store code', status=400)
        # from settings.py, BASE_URL is configured
        BASE_URL = settings.BASE_URL

        store_relative_url = store.get_absolute_url()
        store_absolute_url = BASE_URL + reverse('frontend:detail-store', args=[code])


        # print(store_relative_url, store_absolute_url)

        # Generate the QR code
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=20,
            border=4,
        )
        qr.add_data(store_absolute_url)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")

        # Create an in-memory buffer containing the image data
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        buffer.seek(0)

        base64_image = base64.b64encode(buffer.read()).decode('utf-8')

        context = {
            'data': store_absolute_url,
            'base64_image': base64_image
        }
        html = template.render(context)

        # Create a PDF from the HTML
        result = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html.encode('UTF-8')), result)
        if not pdf.err:
            response = HttpResponse(result.getvalue(), content_type='application/pdf')
            # response['Content-Disposition'] = 'attachment; filename=mypdf.pdf' # is download
            response['Content-Disposition'] = 'inline; filename=qrcode.pdf'
            return response
        return HttpResponse('Error generating PDF', status=400)


class StoreListQrcodeView(LoginRequiredMixin, ListView):
    template_name = 'store/list-store-qrcode.html'
    # queryset = Store.objects.all()
    model = Store

    # context_object_name = 'stores'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        utilisateur = Utilisateur.objects.get(email=self.request.user.email)

        if (self.request.user.is_authenticated and utilisateur.is_admin):
            stores = Store.objects.all()

        else:
            stores = Store.objects.filter(proprietary=utilisateur)
            # stores = Store.objects.all()

        print('utilisateur', utilisateur.id)
        print('store', stores)
        context['stores'] = stores
        return context


class StoreCreateView(LoginRequiredMixin, CreateView, SuccessMessageMixin):
    """Class based view to create a store"""
    template_name = 'store/add-store.html'
    model = Store
    form_class = StoreForm
    context_object_name = 'store'

    success_message = 'Store created successfully'

    def get_success_url(self):
        return reverse('store:list-store')

    def get_form_kwargs(self):
        kwargs = super(StoreCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        objStore = form.save(commit=False)
        objStore.proprietary = Utilisateur.objects.get(email=self.request.user.email)
        objStore.save()
        return super(StoreCreateView, self).form_valid(form)


class StoreUpdateView(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
    """Class based view to update a store"""
    template_name = 'store/edit-store.html'
    model = Store
    form_class = StoreForm
    context_object_name = 'store'

    success_message = 'Store edited successfully'

    def get_success_url(self):
        return reverse('store:list-store')

    def get_object(self, queryset=None):
        """ Hook to ensure object. """
        obj = super(StoreUpdateView, self).get_object()
        return obj

    def get_form_kwargs(self):
        kwargs = super(StoreUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        objStore = form.save(commit=False)
        # objStore.proprietary = Utilisateur.objects.get(email=self.request.user.email)
        objStore.save()

        return super(StoreUpdateView, self).form_valid(form)


class StoreDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    """Class based view to delete a store"""
    model = Store
    template_name = "store/delete-store.html"
    context_object_name = "store"

    success_message = "Store deleted successfully."

    def get_success_url(self):
        return reverse("store:list-store")


class StoreDetailsView(LoginRequiredMixin, DetailView):
    template_name = 'store/detail-store.html'
    model = Store
    context_object_name = 'store'


class ProductListView(LoginRequiredMixin, ListView):
    template_name = 'product/list-product.html'
    # queryset = Store.objects.all()
    model = Product

    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = None

        utilisateur = Utilisateur.objects.get(email=self.request.user.email)

        thestores = Store.objects.filter(proprietary=utilisateur)
        nbre = len(thestores)

        context['has_stores'] = True if nbre > 0 else False

        if (self.request.user.is_authenticated and utilisateur.is_admin):
            products = Product.objects.all()

        else:

            products = Product.objects.select_related('store__proprietary').filter(store__proprietary_id=utilisateur.id)

        context['products'] = products
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    template_name = 'product/add-product.html'
    # queryset = Store.objects.all()
    model = Product
    form_class = ProductForm

    context_object_name = 'product'

    def get_success_url(self):
        return reverse('store:list-product')

    """def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        proprietary = Utilisateur.objects.get(telephone=self.request.user.telephone)

        store = Store.objects.filter(proprietary= proprietary)
        print(type(store))

        context['store'] = store[1]

        return context

        print('proprietary', proprietary)"""

    def get_form_kwargs(self):
        kwargs = super(ProductCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user

        return kwargs


class ProductUpdateView(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
    template_name = 'product/edit-product.html'
    model = Product
    form_class = ProductForm

frontend/templates/frontend/header.html
{% load static %}
<!--[if lte IE 9]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade
    your browser</a> to improve your experience and security.</p>
<![endif]-->
<a href="#top" class="back-to-top" id="backto-top"><i class="fal fa-arrow-up"></i></a>
<header class="header axil-header header-style-1">
    <div class="header-top-campaign">
        <div class="container position-relative">
            <div class="campaign-content">
                <p>CHAPCHAP, quick and well ! <a class="d-none" href="#">Discover More</a></p>
            </div>
        </div>
        <button class="remove-campaign"><i class="fal fa-times"></i></button>
    </div>
    <div class="axil-header-top mt-2">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-sm-6">
                    <div class="header-top-dropdown">
                        <div class="dropdown d-none">
                            <button class="dropdown-toggle" type="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                English
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">English</a></li>
                                <li><a class="dropdown-item" href="#">Arabic</a></li>
                                <li><a class="dropdown-item" href="#">Spanish</a></li>
                            </ul>
                        </div>
                        <div class="dropdown">
                            <button class="dropdown-toggle" type="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                XOF
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">XOF</a></li>
                                <li><a class="dropdown-item" href="#">USD</a></li>
                                <li><a class="dropdown-item" href="#">EUR</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="header-top-link">
                        <ul class="quick-link">
                            <li><a class="d-none" href="#">Help</a></li>
                            <li><a href="{% url 'frontend:signup' %}">Join Us</a></li>
                            <li><a href="{% url 'frontend:login' %}">Sign In</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Start Mainmenu Area  -->
    <div id="axil-sticky-placeholder"></div>
    <div class="axil-mainmenu">
        <div class="container">
            <div class="header-navbar">
                <div class="header-brand">
                    <a href="{% url 'frontend:index' %}" class="logo logo-dark">
                        <img src="{% static 'assets/images/logo/logo.png' %}" alt="Site Logo">
                    </a>
                    <a href="{% url 'frontend:index' %}" class="logo logo-light">
                        <img src="{% static 'assets/images/logo/logo-light.png' %}" alt="Site Logo">
                    </a>
                </div>
                <div class="header-main-nav">
                    <!-- Start Mainmanu Nav -->
                    <nav class="mainmenu-nav">
                        <button class="mobile-close-btn mobile-nav-toggler"><i class="fas fa-times"></i></button>
                        <div class="mobile-nav-brand">
                            <a href="{% url 'frontend:index' %}" class="logo">
                                <img src="{% static 'assets/images/logo/logo.png' %}" alt="Site Logo">
                            </a>
                        </div>
                        <ul class="mainmenu">
                            <li>
                                <a href="{% url 'frontend:index' %}">Home</a>
                                <ul class="axil-submenu d-none">
                                    <li><a href="index-1.html">Home - Electronics</a></li>
                                    <li><a href="index-2.html">Home - NFT</a></li>
                                    <li><a href="index-3.html">Home - Fashion</a></li>
                                    <li><a href="index-4.html">Home - Jewellery</a></li>
                                    <li><a href="index-5.html">Home - Furniture</a></li>
                                    <li><a href="index-6.html">Home - Multipurpose</a></li>
                                    <li><a href="https://new.axilthemes.com/demo/template/etrade-rtl/">RTL Version</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="{% url 'frontend:shop' %}">Shop</a>
                                <ul class="axil-submenu d-none">
                                    <li><a href="shop-sidebar.html">Shop With Sidebar</a></li>
                                    <li><a href="shop.html">Shop no Sidebar</a></li>
                                    <li><a href="single-product.html">Product Variation 1</a></li>
                                    <li><a href="detail-store.html">Product Variation 2</a></li>
                                    <li><a href="single-product-3.html">Product Variation 3</a></li>
                                    <li><a href="single-product-4.html">Product Variation 4</a></li>
                                    <li><a href="single-product-5.html">Product Variation 5</a></li>
                                    <li><a href="single-product-6.html">Product Variation 6</a></li>
                                    <li><a href="single-product-7.html">Product Variation 7</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="{% url 'frontend:stores' %}">Store</a>
                                <ul class="axil-submenu d-none">
                                    <li><a href="shop-sidebar.html">Shop With Sidebar</a></li>
                                    <li><a href="shop.html">Shop no Sidebar</a></li>
                                    <li><a href="single-product.html">Product Variation 1</a></li>
                                    <li><a href="detail-store.html">Product Variation 2</a></li>
                                    <li><a href="single-product-3.html">Product Variation 3</a></li>
                                    <li><a href="single-product-4.html">Product Variation 4</a></li>
                                    <li><a href="single-product-5.html">Product Variation 5</a></li>
                                    <li><a href="single-product-6.html">Product Variation 6</a></li>
                                    <li><a href="single-product-7.html">Product Variation 7</a></li>
                                </ul>
                            </li>
                            <li class="menu-item-has-children d-none">
                                <a href="#">Pages</a>
                                <ul class="axil-submenu d-none">
                                    <li><a href="wishlist.html">Wishlist</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li><a href="my-account.html">Account</a></li>
                                    <li><a href="sign-up.html">Sign Up</a></li>
                                    <li><a href="sign-in.html">Sign In</a></li>
                                    <li><a href="forgot-password.html">Forgot Password</a></li>
                                    <li><a href="reset-password.html">Reset Password</a></li>
                                    <li><a href="privacy-policy.html">Privacy Policy</a></li>
                                    <li><a href="coming-soon.html">Coming Soon</a></li>
                                    <li><a href="404.html">404 Error</a></li>
                                    <li><a href="typography.html">Typography</a></li>
                                </ul>
                            </li>
                            <li><a href="#">About</a></li>
                            <li class="menu-item-has-children d-none">
                                <a href="#">Blog</a>
                                <ul class="axil-submenu">
                                    <li><a href="blog.html">Blog List</a></li>
                                    <li><a href="blog-grid.html">Blog Grid</a></li>
                                    <li><a href="blog-details.html">Standard Post</a></li>
                                    <li><a href="blog-gallery.html">Gallery Post</a></li>
                                    <li><a href="blog-video.html">Video Post</a></li>
                                    <li><a href="blog-audio.html">Audio Post</a></li>
                                    <li><a href="blog-quote.html">Quote Post</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </nav>
                    <!-- End Mainmanu Nav -->
                </div>
                <div class="header-action">
                    <ul class="action-list">
                        <li class="axil-search d-none">
                            <a href="javascript:void(0)" class="header-search-icon" title="Search">
                                <i class="flaticon-magnifying-glass"></i>
                            </a>
                        </li>
                        <li class="wishlist d-none">
                            <a href="wishlist.html">
                                <i class="flaticon-heart"></i>
                            </a>
                        </li>
                        <li class="shopping-cart">
                            <a href="{% url "cart:cart_detail" %}" class="cart-dropdown-btn d-none">zz
                            </a><a href="{% url "cart:cart_detail" %}" class="cart-dropdown-btn">

                                    {% with total_items=cart|length %}
                                        {% if total_items > 0 %}
                                        <span class="cart-count">
                {{ total_items }}


                                        {% else %}
                                            <span class="cart-count d-none">
                                        {% endif %}
                                    {% endwith %}
                                </span>
                                <i class="flaticon-shopping-cart"></i>
                            </a>
                        </li>
                        <li class="my-account d-none">
                            <a href="javascript:void(0)">
                                <i class="flaticon-person"></i>
                            </a>
                            <div class="my-account-dropdown">
                                <span class="title">QUICKLINKS</span>
                                <ul>
                                    <li>
                                        <a href="my-account.html">My Account</a>
                                    </li>
                                    <li>
                                        <a href="#">Initiate return</a>
                                    </li>
                                    <li>
                                        <a href="#">Support</a>
                                    </li>
                                    <li class="d-none">
                                        <a href="#">Language</a>
                                    </li>
                                </ul>
                                <div class="login-btn">
                                    <a href="sign-in.html" class="axil-btn btn-bg-primary">Login</a>
                                </div>
                                <div class="reg-footer text-center">No account yet? <a href="sign-up.html"
                                                                                       class="btn-link">REGISTER
                                    HERE.</a></div>
                            </div>
                        </li>
                        <li class="axil-mobile-toggle">
                            <button class="menu-btn mobile-nav-toggler">
                                <i class="flaticon-menu-2"></i>
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Mainmenu Area -->
</header>

frontend/templates/frontend/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> Test</h1>
</body>
</html>