cart/urls.py
#!/usr/bin/python3
"""here is the urls, the routing of cart application"""
from django.urls import path

from cart.views import (cart_add, cart_remove, cart_detail,)

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove,
         name='cart_remove'),

]

chapchap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('cart/', include('cart.urls')),
    path('myaccount/', include('myaccount.urls')),
    path('orders/', include('orders.urls')),
    path('store/', include('store.urls')),
    path('summernote/', include('django_summernote.urls')), # for summernote
]
if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'frontend.views.page_not_found_view'

myaccount/urls.py
"""routes of myaccount application"""
from django.contrib.auth.views import LogoutView
from django.urls import path

import myaccount
from myaccount.views import dashboard
app_name = 'myaccount'

urlpatterns = [
    path('dashboard/',dashboard, name='dashboard'),
    path('logout/', LogoutView.as_view(), name='logout'),  # extending  Django built in logout
]

store/urls.py
#!/usr/bin/python3
"""here is the urls, the routing of store application"""
from django.urls import path

from store.views import (StoreListView, StoreCreateView, StoreUpdateView,
                         ProductListView, ProductCreateView,
                         ProductUpdateView, StoreDeleteView,
                         ProductDeleteView, StoreListQrcodeView, MyView,
                         MyViewPdf, QRcodeView)

app_name = 'store'

urlpatterns = [
    path('list-store/', StoreListView.as_view(), name='list-store'),
    path('list-store-qrcode/', StoreListQrcodeView.as_view(), name='list-store-qrcode'),
    path('generate-qrstore/', MyView.as_view(), name='generate-qrstore'),
    path('generate-pdf/<uuid:code>', MyViewPdf.as_view(), name='generate-pdf'),
    # path('generate-pdf/', MyViewPdf.as_view(), name='generate-pdf'),
    path('generate-qrstore-pdf/', QRcodeView.as_view(), name='generate-qrstore-pdf'),
    path('add-store/', StoreCreateView.as_view(), name='add-store'),
    path('edit-store/<int:pk>', StoreUpdateView.as_view(), name='edit-store'),
    path('delete-store/<int:pk>', StoreDeleteView.as_view(), name='del-store'),
    path('list-product/', ProductListView.as_view(), name='list-product'),
    path('add-product/', ProductCreateView.as_view(), name='add-product'),
    path('edit-product/<int:pk>', ProductUpdateView.as_view(),
         name='edit-product'),
    path('delete-product/<int:pk>', ProductDeleteView.as_view(),
         name='del-product'),

]

myaccount/views.py
"""controller actions, """
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render

# Create your views here.
from frontend.models import Utilisateur


@login_required(login_url='/login')
def dashboard(request):
    """Show dashboard after a successful login"""

    utilisateur = Utilisateur.objects.get(email=request.user.email)
    context = {
        'request': request
    }
    return render(request, 'myaccount/dashboard.html', context)

myaccount/templates/myaccount/aside.html
<div class="nav nav-tabs" role="tablist">
    <a class="nav-item nav-link active" href="{% url 'myaccount:dashboard' %}"><i
            class="fas fa-th-large"></i>Dashboard</a>
    <a class="nav-item nav-link" href="{% url 'store:list-store' %}" role="tab" aria-selected="false"><i
            class="fas fa-shopping-bag"></i>My Stores</a>
        {% if has_stores %}
            <a class="nav-item nav-link d-none" href="{% url 'store:list-store-qrcode'%}" role="tab"><i
            class="fas fa-file-download"></i>My QRcodes</a>
            <a class="nav-item nav-link" href="{% url 'store:list-product' %}" role="tab" aria-selected="false"><i
            class="fas fa-shopping-basket"></i>Products</a>

        {% endif %}
    <a class="nav-item nav-link" href="#"><i
            class="fas fa-file-download"></i>Orders</a>
    {% comment %}<a class="nav-item nav-link" data-bs-toggle="tab" href="#nav-downloads" role="tab" aria-selected="false"><i
            class="fas fa-file-download"></i>Downloads</a>
    <a class="nav-item nav-link" data-bs-toggle="tab" href="#nav-address" role="tab" aria-selected="false"><i
            class="fas fa-home"></i>Addresses</a>
    <a class="nav-item nav-link" data-bs-toggle="tab" href="#nav-account" role="tab" aria-selected="false"><i
            class="fas fa-user"></i>Account Details</a>{% endcomment %}
    <a class="nav-item nav-link" href="{% url 'myaccount:logout' %}"><i class="fal fa-sign-out"></i>Logout</a>
</div>

myaccount/templates/myaccount/cart-dropdown.html
<div class="cart-dropdown" id="cart-dropdown">
        <div class="cart-content-wrap">
            <div class="cart-header">
                <h2 class="header-title">Cart review</h2>
                <button class="cart-close sidebar-close"><i class="fas fa-times"></i></button>
            </div>
            <div class="cart-body">
                <ul class="cart-item-list">
                    <li class="cart-item">
                        <div class="item-img">
                            <a href="single-product.html"><img src="assets/images/product/electric/product-01.png" alt="Commodo Blown Lamp"></a>
                            <button class="close-btn"><i class="fas fa-times"></i></button>
                        </div>
                        <div class="item-content">
                            <div class="product-rating">
                                <span class="icon">
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
							</span>
                                <span class="rating-number">(64)</span>
                            </div>
                            <h3 class="item-title"><a href="single-product-3.html">Wireless PS Handler</a></h3>
                            <div class="item-price"><span class="currency-symbol">$</span>155.00</div>
                            <div class="pro-qty item-quantity">
                                <input type="number" class="quantity-input" value="15">
                            </div>
                        </div>
                    </li>
                    <li class="cart-item">
                        <div class="item-img">
                            <a href="single-product-2.html"><img src="assets/images/product/electric/product-02.png" alt="Commodo Blown Lamp"></a>
                            <button class="close-btn"><i class="fas fa-times"></i></button>
                        </div>
                        <div class="item-content">
                            <div class="product-rating">
                                <span class="icon">
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
							</span>
                                <span class="rating-number">(4)</span>
                            </div>
                            <h3 class="item-title"><a href="single-product-2.html">Gradient Light Keyboard</a></h3>
                            <div class="item-price"><span class="currency-symbol">$</span>255.00</div>
                            <div class="pro-qty item-quantity">
                                <input type="number" class="quantity-input" value="5">
                            </div>
                        </div>
                    </li>
                    <li class="cart-item">
                        <div class="item-img">
                            <a href="single-product-3.html"><img src="assets/images/product/electric/product-03.png" alt="Commodo Blown Lamp"></a>
                            <button class="close-btn"><i class="fas fa-times"></i></button>
                        </div>
                        <div class="item-content">
                            <div class="product-rating">
                                <span class="icon">
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
							</span>
                                <span class="rating-number">(6)</span>
                            </div>
                            <h3 class="item-title"><a href="single-product.html">HD CC Camera</a></h3>
                            <div class="item-price"><span class="currency-symbol">$</span>200.00</div>
                            <div class="pro-qty item-quantity">
                                <input type="number" class="quantity-input" value="100">
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="cart-footer">
                <h3 class="cart-subtotal">
                    <span class="subtotal-title">Subtotal:</span>
                    <span class="subtotal-amount">$610.00</span>
                </h3>
                <div class="group-btn">
                    <a href="cart.html" class="axil-btn btn-bg-primary viewcart-btn">View Cart</a>
                    <a href="checkout.html" class="axil-btn btn-bg-secondary checkout-btn">Checkout</a>
                </div>
            </div>
        </div>
    </div>